version: "3.3"

services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    env_file:
      - ./environment    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${TREAFIK_HOSTNAME}`)"
      - "traefik.http.routers.whoami.entrypoints=${TREAFIK_ENTRYPOINT}"
      - "traefik.http.routers.whoami.tls.certresolver=${TREAFIK_CERT_RESOLVER}"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_proxy      